#!/bin/sh
export JSON_STRING='window.configs = { \
  "VITE_APP_API_BASE_URL":"'${VITE_APP_API_BASE_URL}'", \
  "VITE_APP_USE_SENTRY":"'${VITE_APP_USE_SENTRY}'", \
  "VITE_APP_SENTRY_DSN":"'${VITE_APP_SENTRY_DSN}'", \
  "VITE_APP_FACEBOOK_APP_ID":"'${VITE_APP_FACEBOOK_APP_ID}'", \
  "VITE_APP_WHATSAPP_FACEBOOK_APP_ID":"'${VITE_APP_WHATSAPP_FACEBOOK_APP_ID}'", \
  "VITE_APP_WHATSAPP_FACEBOOK_APP_CONFIG_ID":"'${VITE_APP_WHATSAPP_FACEBOOK_APP_CONFIG_ID}'", \
  "VITE_APP_LOGROCKET_ID":"'${VITE_APP_LOGROCKET_ID}'", \
  "VITE_APP_PARENT_IFRAME_DOMAIN":"'${VITE_APP_PARENT_IFRAME_DOMAIN}'", \
  "VITE_APP_HELPHERO_ID":"'${VITE_APP_HELPHERO_ID}'", \
  "VITE_APP_FLOWS_IFRAME_URL":"'${VITE_APP_FLOWS_IFRAME_URL}'", \
  "VITE_APP_HOTJAR_ID":"'${VITE_APP_HOTJAR_ID}'", \
}'
sed "s|//CONFIGURATIONS_PLACEHOLDER|${JSON_STRING}|" /usr/share/nginx/html/integrations/index.html.tmpl > /tmp/index.html

exec "$@"